server:
  port: 8761

spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


eureka:
  client:
    register-with-eureka: false    # 자기 자신은 등록 안 함
    fetch-registry: false          # 레지스트리 가져오지 않음
  server:
    enable-self-preservation: false  # 개발 환경에서는 끔